# -*- coding: utf-8 -*-
"""Копія записника "Solving a Problem Using Open Data.ipynb"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1F9usxRNf8dhfvN3EngDH6wm7XWjPMPgF
"""

"""
Project: Hazardous Waste Analysis in Lithuania
"""

import pandas as pd
import matplotlib.pyplot as plt
import json


# ================================================================
# Data Loading
# ================================================================
def load_json_data(path: str) -> pd.DataFrame:
    """Load dataset from JSON file and convert to DataFrame with error handling."""
    try:
        with open(path, "r", encoding="utf-8") as f:
            raw = json.load(f)

    except FileNotFoundError:
        print(f"File not found: {path}")
        print("Please upload the file or check the path.")
        return None

    except json.JSONDecodeError as e:
        print(f"Error decoding JSON: {e}")
        print("Make sure the file contains valid JSON.")
        return None

    except Exception as e:
        print(f"Unexpected error while loading file: {e}")
        return None

    try:
        df = pd.DataFrame(raw["_data"])
    except KeyError:
        print("JSON file does not contain expected key '_data'.")
        return None

    return df


# ================================================================
# Preprocessing
# ================================================================
def preprocess_data(df: pd.DataFrame) -> pd.DataFrame:
    """Clean and keep relevant columns."""

    cols = ["metai", "atl_pavad", "pavojingumas",
            "surinkta", "susidare", "perdirbimas"]

    df = df[cols].copy()

    # Fill numeric columns
    num_cols = ["surinkta", "susidare", "perdirbimas"]
    df[num_cols] = df[num_cols].fillna(0)

    return df


# ================================================================
# Data Processing / Indicators
# ================================================================
def compute_total_by_year(df: pd.DataFrame) -> pd.DataFrame:
    """Calculate total collected waste per year."""
    return df.groupby("metai")["surinkta"].sum().reset_index()


def compute_hazard_split(df: pd.DataFrame) -> pd.DataFrame:
    """Compute hazardous vs. non-hazardous waste share per year."""
    hazard_split = df.groupby(["metai", "pavojingumas"])["surinkta"].sum().reset_index()

    pivot = hazard_split.pivot(index="metai",
                               columns="pavojingumas",
                               values="surinkta").fillna(0)

    pivot.columns = ["Non-hazardous", "Hazardous"]

    pivot["Hazardous %"] = (
        pivot["Hazardous"] / (pivot["Hazardous"] + pivot["Non-hazardous"])
    ) * 100

    return pivot


# ================================================================
# Visualizations
# ================================================================
def plot_total_by_year(total_df: pd.DataFrame) -> None:
    """Line plot of total collected waste over time."""
    plt.figure(figsize=(8, 5))
    plt.plot(total_df["metai"], total_df["surinkta"], marker="o", label="Total collected")
    plt.title("Total Collected Waste in Lithuania")
    plt.xlabel("Year")
    plt.ylabel("Collected waste (tonnes)")
    plt.grid(True)
    plt.legend()
    plt.tight_layout()
    plt.show()


def plot_hazard_split(hazard_df: pd.DataFrame) -> None:
    """Stacked bar chart: hazardous vs non-hazardous waste."""
    hazard_df[["Non-hazardous", "Hazardous"]].plot(
        kind="bar", stacked=True, figsize=(9, 6)
    )
    plt.title("Hazardous vs Non-Hazardous Waste Collected")
    plt.xlabel("Year")
    plt.ylabel("Collected waste (tonnes)")
    plt.tight_layout()
    plt.show()


def plot_hazard_share(hazard_df: pd.DataFrame) -> None:
    """Line plot of hazardous waste share over time."""
    plt.figure(figsize=(8, 5))
    plt.plot(hazard_df.index, hazard_df["Hazardous %"], marker="o")
    plt.title("Hazardous Waste Share (%) Over Time")
    plt.xlabel("Year")
    plt.ylabel("Hazardous share (%)")
    plt.grid(True)
    plt.tight_layout()
    plt.show()


# ================================================================
# Main Workflow
# ================================================================
def main(json_path="json.json"):
    """Main entry point: load, process, display, visualize."""

    df = load_json_data(json_path)
    if df is None:
        print("Program stopped because the dataset could not be loaded.")
        return

    df = preprocess_data(df)

    # Calculations
    total_by_year = compute_total_by_year(df)
    hazard_pivot = compute_hazard_split(df)

    # Print results
    print("Total collected waste by year:")
    print(total_by_year.head(10))

    print("\nHazardous waste share (%):")
    print(hazard_pivot[["Hazardous %"]].head(10))

    # Visualizations
    plot_total_by_year(total_by_year)
    plot_hazard_split(hazard_pivot)
    plot_hazard_share(hazard_pivot)

# ================================================================
# Script Entry Point
# ================================================================
if __name__ == "__main__":
    main()



"""# Новий розділ"""