# -*- coding: utf-8 -*-
"""Programukurimuprocesas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14owhx0-n469Eu5kMY3mb_ORa2WsSnoLn

!pip install pandas openpyxl
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt


class EnergyTemperatureAnalyzer:

    def __init__(self, energy_file, temperature_file, building_types):

        self.energy_file = energy_file
        self.temperature_file = temperature_file
        self.building_types = building_types

        self.energy_data = None
        self.temperature_data = None
        self.merged_data = {}

    def load_data(self):
        # importinam  duomenis
        self.energy_data = pd.read_excel(self.energy_file, sheet_name=None)
        self.temperature_data = pd.read_excel(self.temperature_file)

    def clean_data(self):

        # ismetam tuscias eilutes
        self.temperature_data.dropna(how='all', inplace=True)
        for name, df in self.energy_data.items():
            df.dropna(how='all', inplace=True)

        # standartizuojam datas
        self.temperature_data['date'] = pd.to_datetime(self.temperature_data['date']).dt.date
        for name, df in self.energy_data.items():
            df['Date'] = pd.to_datetime(df['Date']).dt.date

    def merge_data(self):
        # sujungiam
        self.merged_data = {}
        for name, df in self.energy_data.items():
            merged = pd.merge(
                df[['Date', 'Average']],
                self.temperature_data[['date', 'tavg']],
                left_on='Date',
                right_on='date',
                how='inner'
            )
            self.merged_data[name] = merged

    def plot_per_building(self):
        # vizualizuojam energijos vartojima palyginus su temperatura kiekvienam pastatui
        for name, df in self.merged_data.items():
            plt.figure(figsize=(8, 5))
            sns.scatterplot(x='tavg', y='Average', data=df)
            sns.regplot(x='tavg', y='Average', data=df, scatter=False, color='red')
            plt.title(f'Energija / Temperatura: {name}')
            plt.xlabel("Vidutine paros temperatura (°C)")
            plt.ylabel("Paros energijos suvartojimas (kWh)")
            plt.show()

    def plot_by_building_type(self):
       # vizualizuojam energijos vartojima palyginus su temperatura pagal pastato tipus
        all_buildings = []
        for name, df in self.merged_data.items():
            df['Building'] = name
            df['Type'] = self.building_types.get(name, 'Unknown')
            all_buildings.append(df)

        combined_df = pd.concat(all_buildings)

        g = sns.lmplot(x='tavg', y='Average', hue='Type', data=combined_df, aspect=1.5, scatter=False )
        g.set_axis_labels("Temperatura (°C)", "Energijos suvartojimas (kwH)")
        plt.show()

# kiekvienam energijos sheet'ui priskiriam viena is pastatu tipu
if __name__ == "__main__":
    building_types = {
        'Apartment 1': 'Apartment',
        'Apartment 2': 'Apartment',
        'Apartment 3': 'Apartment',
        'Supermarket 1': 'Supermarket',
        'Supermarket 2': 'Supermarket',
        'Supermarket 3': 'Supermarket',
        'School 1': 'School',
        'School 2': 'School'
    }

  # vykdom
    analyzer = EnergyTemperatureAnalyzer(
        energy_file='/content/excelio_failai/Electricity.xlsx',
        temperature_file='/content/excelio_failai/Temperature.xlsx',
        building_types=building_types
    )

    analyzer.load_data()
    analyzer.clean_data()
    analyzer.merge_data()
    analyzer.plot_per_building()
    analyzer.plot_by_building_type()