# -*- coding: utf-8 -*-
"""Programukurimuprocesas.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14owhx0-n469Eu5kMY3mb_ORa2WsSnoLn
"""

!pip install pandas openpyxl

import pandas as pd

df1 = pd.read_excel('/excelio_failai/Electricity-consumption-by-building-type 1.xlsx')
df1.dropna(inplace = True) # ismetam tuscias eilutes
print("Temperaturos statistika")
display(df1.head(10))

df2 = pd.read_excel('/excelio_failai/export.xlsx')
df2.dropna(inplace = True) # ismetam tuscias eilutes
print("Elektros naudojimas pagal pastatu tipa")
display(df2.head(10))